- name: Variable Prefences
  hosts: local
  connection: local
  # vars: 
  #   NAME: "Ansible From PLAY"
  # vars_files:
  #   - course(5).yaml
  # vars_prompt:
  #   - name: NAME
  #     prompt: please enter your username
  #     private: false
  tasks: 
    - name: print name
      # vars:
      #   NAME: "Ansible from TASK"
      ansible.builtin.debug:
        msg: "HELLOW {{NAME}}"

# 1. ARGS
# 2. TASKS
# 3. FILES
# 4. Prompt
# 5. Play
# 6. Inventory
