- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ansible, terraform 
    course: "DevOps With AWS"
    myIP: 255.456.657.879
    tagsMap: 
      name: Ansible
      project: Roboshop
      component: Catalogue
    tagsList: [
      {
            "key": "name",
            "value": "Ansible"
        },
        {
            "key": "project",
            "value": "Roboshop"
        },
        {
            "key": "component",
            "value": "Catalogue"
        }
    ]

  tasks: 
    - name: greeting
      ansible.builtin.debug:
        msg: "Hi Vasa Rani, {{ GREETING | default('Very Good Morning') }}"

    - name: convert string to list
      ansible.builtin.debug:
        msg: "{{ topics | split(',') }}"
    - name: convert map to list 
      ansible.builtin.debug:
        msg: "{{ tagsMap | dict2items }}"    
    - name: convert list to maps 
      ansible.builtin.debug:
        msg: "{{ tagsList | items2dict }}"
    - name: read info yaml
      ansible.builtin.set_fact: # setting the variable
        info_yaml: "{{ lookup('file', 'info.yaml') | from_yaml }}"
    - name: convert yaml to json
      ansible.builtin.debug:
        msg: "{{ info_yaml | to_nice_json }}"  

    - name: convert to upper case
      ansible.builtin.debug:
        msg: "{{ course | upper }}" 
    - name: convert to lower case
      ansible.builtin.debug:
        msg: "{{ course | lower }}"                
    
    - name: check my IP
      ansible.builtin.debug:
        msg: "{{ myIP | ansible.utils.ipv4 }}" 