- name: demo on error handling
  hosts: local
  connection: local
  tasks: 
    - name: check user exist or not
      ansible.builtin.command: id roboshop 
      register: users_output 
      ignore_error: true

    - name: print the output 
      ansible.builtin.debug:
        msg: "{{users_output}}"  
