- name: play level variables
  hosts: local
  connection: local
  vars_files:
   - course(5).yaml
  tasks: 
   - name: print variables 
     vars:
       course: DOCKERS
     ansible.builtin.debug:
        msg: "Course is {{course}},Duration is: {{duration}}"   